# Generated by Django 3.0.3 on 2020-10-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20201004_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered',
            new_name='complete',
        ),
    ]
