# Generated by Django 3.0.3 on 2020-10-06 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20201006_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='digital',
        ),
    ]
